### PR TITLE
add switch to use roles defined *.aichat files

### PR DESCRIPTION
**Pull request by Konfekt**
[The wiki](https://github.com/madox2/vim-ai?tab=readme-ov-file#custom-commands) suggests defining a custom command for every role, but more convenient would be listing them inside a text file (using the simple aichat format for compatibility) which are then loaded inside a dictionary.

### CODE REVIEW

**Comment by madox2** [comment]
I think you are right, we need a better way how to configure repetitive user prompts (I would rather call it prompts or commands than roles). However when I think more about it, I would implement it in a slightly different way and it is quite a big thing.

This is the high-level idea:

User would be able to specify prompt for any of AI/AIE/AIC commands in a discord-like command fashion, for example:

`:AIE /refactor`

I would keep configuration per each prompt in a single file and with a similar (or identical) format as `.aichat` files. For example it could be `refactor.aiprompt` file:

```
[prompt-options]
temperature=0.2

>>> prompt

You are a Clean Code expert, I have the following code, please refactor it in a more clean and concise way so that my colleagues can maintain the code more easily. Also, explain why you want to refactor the code so that I can add the explanation to the Pull Request.
```

Then there would be a config specifying prompt directory `vim_ai_prompts_dir` and prompts would be referenced by the filename.

Furthermore, this way it would be easy to implement functionality that would execute prompt directly from a file, it could look like this:

`:AI file:/home/user/my_prompt.aiprompt`

**Comment by Konfekt** [comment]
> (I would rather call it prompts or commands than roles).

Since prompt as a term is overloaded (initial, system, instruction prompt ...) and role describes the typical use case well, it is clearer a term. I'd be happy with a bunch of `~/.vim/roles/*.aichat` files and a check that these `aichat` files only contain user options and input (a monologue rather than chat dialogue). 

If we might agree that they are read in as a prompts dictionary as already implemented in this pull request, then the function to read in the `aichat` roles file can be kept as a convenience.

**Comment by madox2** [comment]
The term `role` is already used for `user`, `assistant`, `system` in context of open ai. Therefore I would prefer something else, maybe an `instruction` would be a good name for it.

If not overhead, it would be better if instruction files are loaded on demand so that user does not have to restart vim when adding new instruction.

The point of keeping `aichat`-file like syntax is that we could re-use file parsing functionality that is currently implemented in python. It would be easier to maintain one parsing code than two. Also code highlighting would work the same way.

**Comment by Konfekt** [comment]
> The term role is already used for user, assistant, system in context of open ai

Albeit overloaded by Openai, role is usually understood an initial user instruction/prompt for playing a given role, whereas instruction and prompt have a more general meaning. If role doesn't cut it, how about something more specific such as `directives` or `inits` to make the meaning of an initial user instruction clearer.

> If not overhead, it would be better if instruction files are loaded on demand so that user does not have to restart vim when adding new instruction. 
The point of keeping aichat-file like syntax is that we could re-use file parsing functionality that is currently implemented in python. It would be easier to maintain one parsing code than two. Also code highlighting would work the same way.

I think there's a slight misunderstanding. Using `aichat` files to pass the initial user instructions is great, I just wanted to ask how they are stored internally? I'd propose a simple dictionary such as `g:vim_ai_inits` whose entry `refactorer` can be accessed by `g:vim_ai_inits.refactorer.prompt`, say.

Then this function can be buried somewhere in the `autoload` folder, if permissions is granted, or even outsourced to the wiki.

**Comment by madox2** [comment]
What distracts me with `role` term is that it suggest a subject/noun rather than instruction/verb that needs to be done. But in the end I am fine with both `instruction` and `role`, whatever suits you best.

Internal dictionary is okay as a first step, but it would be better if the file is read directly by the AI command. That way you could modify the file, create a new one and use it without reloading the dictionary.

**Comment by Konfekt** [comment]
> What distracts me with role term is that it suggest a subject/noun rather than instruction/verb that needs to be done.

How about `guideline` or `simulation`? I think I like `guideline`.  

> Internal dictionary is okay as a first step, but it would be better if the file is read directly by the AI command. That way you could modify the file, create a new one and use it without reloading the dictionary.

Yes, fully agreed upon. One can still supplement the `files_dict` by a personal dict `user_dict` by appending a user supplied one: `call extend(files_dict, user_dict)`.

**Comment by madox2** [comment]
I think I would rather prefer `instruction` or `role`.

**Comment by Konfekt** [comment]
While trying to wrap my head around how to call 

```py
#  py/utils.py (lines 165-186)
def parse_chat_header_options():
    try:
        options = {}
        lines = vim.eval('getline(1, "$")')
        contains_chat_options = '[chat-options]' in lines
        if contains_chat_options:
            # parse options that are defined in the chat header
            options_index = lines.index('[chat-options]')
            for line in lines[options_index + 1:]:
                if line.startswith('#'):
                    # ignore comments
                    continue
                if line == '':
                    # stop at the end of the region
                    break
                (key, value) = line.strip().split('=')
                if key == 'initial_prompt':
                    value = value.split('\\n')
                options[key] = value
        return options
    except:
        raise Exception("Invalid [chat-options]")
```

inside Vim (on every file in a roles folder), in the meanwhile the code has been updated to reload the config on every invocation and provide role variants for all commands.

**Comment by madox2** [comment]
One thing I want to avoid is adding new commands `AIEditAs`, `AIChatAs`. That would break shorthands like `:AIE`, `:AIC` that I find very useful. How about optional role passed to existing commands. For example `:AIE /review`

**Comment by Konfekt** [comment]
> How about optional role passed to existing commands. For example :AIE /review

Indeed a very fine idea, that now is implemented.

> That would break shorthands like :AIE, :AIC that I find very useful. 

May I propose [vim-alias](https://github.com/Konfekt/vim-alias) ? I am using aliases like `Alias -range ae AIEdit` excessively. Now there is also

```vim
function! EatChar(pat)
  let c = nr2char(getchar(0))
  return (c =~ a:pat) ? '' : c
endfunction
Alias -range aea AIEdit\ /<c-r>=&spell||empty(&filetype)?'':'\ In\ '.&filetype.':'<cr><home><c-right><c-right><C-R>=EatChar('\s').nr2char(&wildcharm)<CR>
```

to run through the roles.

**Comment by Konfekt** [comment]
As suggested above, the plug-in now defaults to reading the roles from a set of `vim_ai/roles/*.aichat` files. This pull request should be feature complete.

**Comment by madox2** [comment]
Hi, thanks for all the effort! I was thinking lately and I would like to implement this feature in a slightly different way. I am going to push my branch soon, it would be great if you could test it then. I will keep you posted

**Comment by Konfekt** [comment]
Feel free. I'd be happy if compatibility with the dictionary can be kept so that an alternative source, here a single file, can be used. It's been working very well on my end.

**Pull request closed without merging**
