### PR TITLE
fix selection include extra content when the user is in visual mode

### PR DESCRIPTION
**Pull request by cposture**

### CODE REVIEW

**Comment by cposture** [comment]
This is the effect of the demonstration after I modified it. It only show the AIEdit command. Other commands are also normal.


https://github.com/madox2/vim-ai/assets/8305198/b11fbad6-a7af-41a6-bbb1-2065d7c3bb9f

**Comment by cposture** [comment]
@madox2

**Comment by madox2** [comment]
Hi, thank you for the contribution, this looks really cool! I need some time to test it but I think it would be a great improvement

**Comment by madox2** [comment]
So far I found one issue. It seems that when using multiline selection it somehow spoils the last line:
AIE_correct

This is how it is intended to work:
AIE_correct

**Comment by cposture** [comment]
I think there is a problem with the completion script; each line has a newline character at the end, and multi-line selection includes the last newline character, which the completion script should keep. Let me see how to fix this issue.
@madox2

**Comment by madox2** [comment]
Thank you very much for your work!

I am not sure I fully understand the 2nd case yet, but I will deep dive into the code as soon as I finish testing.

There is also another issue with an empty line, the video below shows how to reproduce + how it is supposed to work on main branch.
AIE_issue2

**Comment by cposture** [comment]
@madox2 I've made a bug fix in the `RangeSelect` method，please review code

In the 'visual mode' scenario, initially I had used a complex function `call s:RangeSelect(getpos("'<")[1:2], getpos("'>")[1:2])` to start Visual mode with the same area as the previous area and the same mode. However, upon further investigation, I discovered that `execute "normal! gv"` was a simpler solution that fulfilled the same requirements, and thus fixed the original bug. Less is more!

**Comment by madox2** [comment]
I have done my tests and reviewed the code, it all looks good, great job! Thanks again for the contribution and collaboration!

**Pull request merged**
