### PR TITLE
small improvements

### PR DESCRIPTION
**Pull request by thiswillbeyourgithub**
Hi!
Great project! Huge time saver IMO.

I prefer using chatgpt instead of davinci for completion so I figured I'd make a quick PR. Let me know what you think!

- improvement: print output less frequently to avoid cluttering the undo tree
- feat: add support for chatgpt for completion
- docs: mention how to manually install
- docs: clearer documentation on how to continue chat
- feat: better completion default, importantly : use chatgpt instead of davinci for completion as its 10 times cheaper

cheers

### CODE REVIEW

**Comment by madox2** [comment]
Thank you so much for the contribution! I am currently working on chat integration into complete/edit commands but in a slightly different way. So unfortunately I cannot merge this as it would conflict with my implementation. This will be available soon, I will keep you posted! I will also get inspired by your changes and incorporate them later.

One thing that caught my attention is how you throttle openai responses. What do you mean by "cluttering the undo tree"? In what way is that a problem when using VIM?

**Comment by madox2** [comment]
Thanks for the inspiring ideas! I would like to keep chat to start new conversation and chat on a new topic every time. To persist and restore conversation, you can simply store it in .aichat file, open it next time and continue chatting. This way you can manage as many conversations/topic as you want.

I am very curious why is the undo tree cluttered in your case. When I undo in chat (or after completion) it undoes the whole answer at once. What kind of vim/nvim and OS are u using?

**Comment by thiswillbeyourgithub** [comment]
I want the chat to be saved by default instead of having to save it manually to an aichat file. I frequently close the chat too early and figure out later that I need some more etc.

Regarding the undo tree, I'm using neovim 0.6.1 on ubuntu 22.

**Comment by madox2** [comment]
I see. Btw you can also find last chat in the open buffers. But give me some time to think about it, maybe a config option to restore last chat window and to persist chat to a file would make sense.

Regarding the undo tree, thanks for the details, I will try to replicate and sort it out

**Comment by madox2** [comment]
Just for the record, I've just tested the undo in chat on Debian 11, NVIM v0.8.3 and it works as expected - undoes the whole assistant response in one shot

**Comment by madox2** [comment]
Hi again, you might find useful configuring edit/complete commands with chat endpoint:
https://github.com/madox2/vim-ai#using-chat-engine-for-completion-and-edits 

I have also added an option to configure chat window, you can use it to restore last conversation:
https://github.com/madox2/vim-ai#interface-configuration

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot, I'll switch to your code and make new issues or PR if I have anything relevant to add if that's okay :) 

Some commits still feel relevant : 
d8600c1fd6fa5f6a0e669a9006c98f3c8dd59281
375cae183db5e4ba713d1396a072747348978d26

**Comment by thiswillbeyourgithub** [comment]
I think you also left out the commit that wrapped the text.

**Comment by madox2** [comment]
Hi, to be honest I am not sure if I should set `wrap` in the chat window. In the environments I am testing vim-ai, it is automatically wrapping lines without explicitly setting it. So first I'd like to understand why is it not wrapping lines in your case - do you have set `nowrap` in vimrc by default and need just chat window to wrap lines?

**Comment by thiswillbeyourgithub** [comment]
Indeed by default I have "set nowrap" in my init.vim. I think most people would prefer wrap enabled in the chat window regardless of their default behavior.

**Comment by madox2** [comment]
I see. I don't want vim-ai to be overriding default user settings. If you need a specific setting for a certain type of file (.aichat in this case), you should be able to configure that with [autocmd](https://github.com/vim/vim/blob/master/runtime/doc/autocmd.txt). Another reason to not do that is that scratch window might behave differently than .aichat files.

**Comment by madox2** [comment]
I don't see this PR relevant anymore, let's continue discussion about cluttered undo tree in #14

**Pull request closed without merging**
